# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 3000

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[▊ I ❯](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
vimcmd_symbol = '[▊ N ❯](bold blue)'
error_symbol = '[✗](bold red)'
vimcmd_visual_symbol = '[V](bold purple)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[gcloud]
disabled = true

[aws]
disabled = true
